# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e7cdb8ab5691caa4b3f0662bdbafaed707167937fe14c6732d831ae02407fab884723d6b15c4f2654a391d65ff444fe401c143b1b334012380876d96e37cdf

test:
  secret_key_base: efdc638e0b9d6466c9b5c076b4da7bc4d6956d734328551cf648037d3216c35be76792488e515120d8f74ba3812c5f2837e015f8bb09751253fbed38c4ec4e47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
